version: '3'
services:
  web:
    image: node:16
    container_name: web
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"  
    volumes:
      - .:/app 
    working_dir: /app
    environment:
      - NEXT_PUBLIC_DB_URL=postgresql://postgres:postgres@db:5432/todolist?schema=public  
    depends_on:
      - db  
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todolist  
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data  

volumes:
  postgres_data:  
